name: Deploy to Cloud Run

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Build and Push Image
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/xero-sync

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy xero-sync \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/xero-sync \
          --platform managed \
          --region asia-southeast1 \
          --set-env-vars "XERO_CLIENT_ID=${{ secrets.XERO_CLIENT_ID }}" \
          --set-env-vars "XERO_CLIENT_SECRET=${{ secrets.XERO_CLIENT_SECRET }}" \
          --set-env-vars "XERO_REDIRECT_URI=${{ secrets.XERO_REDIRECT_URI }}" \
          --set-env-vars "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" \
          --set-env-vars "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}"
